


server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/operational_loss_db
    username: postgres
    password: admin123

  flyway:
    enabled: true
    baseline-on-migrate: true